const tr = globalThis.BlockItUI18n.t;
const reloadCount=document.getElementById('reloadCount'),stabilityEnabled=document.getElementById('stabilityEnabled'),startAudit=document.getElementById('startAudit'),siteText=document.getElementById('siteText'),resultsList=document.getElementById('resultsList'),summary=document.getElementById('summary'),progressPanel=document.getElementById('progressPanel'),progressTitle=document.getElementById('progressTitle'),progressDetail=document.getElementById('progressDetail'),progressBar=document.getElementById('progressBar');
for(let value=2;value<=9;value++){const option=document.createElement('option');option.value=value;option.textContent=value;option.selected=value===3;reloadCount.append(option)}
let draft=null;
function ruleLabel(rule){if(rule.type==='blockitbuilder'){try{const model=rule.builderModel||globalThis.__blockItRuleModel.parse(rule.selector);return rule.displaySelector||globalThis.__blockItRuleModel.toDisplaySelector(model)}catch{return tr('Некорректное правило конструктора')}}return rule.selector||tr('Правило без записи')}
function selectedRuns(){return stabilityEnabled.checked?Number(reloadCount.value):1}
function updateTooltip(){const count=selectedRuns();reloadCount.disabled=!stabilityEnabled.checked;const text=stabilityEnabled.checked?tr('Страница сайта {site} будет перезагружена {count} раз. Во время проверки правила BlockIt временно не применяются.',{site:draft?.domain||'',count}):tr('Страница сайта {site} будет перезагружена один раз. Проверка стабильности отключена.',{site:draft?.domain||''});startAudit.removeAttribute('title');startAudit.dataset.tooltip=text;startAudit.setAttribute('aria-description',text)}
function updateStability(){updateTooltip();if(draft)renderInitial()}
reloadCount.addEventListener('change',updateStability);stabilityEnabled.addEventListener('change',updateStability);
function waitForReload(tabId){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{chrome.tabs.onUpdated.removeListener(listener);reject(new Error(tr('Страница загружается слишком долго')))},30000);const listener=(id,change)=>{if(id===tabId&&change.status==='complete'){clearTimeout(timer);chrome.tabs.onUpdated.removeListener(listener);resolve()}};chrome.tabs.onUpdated.addListener(listener)})}
function countRulesInPage(rules){let host=location.hostname.replace(/^www\./,'').toLowerCase();if(!host){try{host=new URL(location.ancestorOrigins?.[0]).hostname.replace(/^www\./,'').toLowerCase()}catch{}}return rules.map(rule=>{const ruleDomain=String(rule.domain||'').replace(/^www\./,'').toLowerCase();if(ruleDomain&&host!==ruleDomain&&!host.endsWith(`.${ruleDomain}`))return{count:0};try{if(rule.type==='blockitbuilder'){const model=rule.builderModel||globalThis.__blockItRuleModel.parse(rule.selector);return{count:globalThis.__blockItRuleModel.find(model).length}}if(rule.type==='stablehtmlfinder'){const target=rule.stableRule?.target;return{count:target?.selector?globalThis.__blockItSelectorEngine.find(target.selector).length:0}}if(rule.type==='xpath'){const xpath=String(rule.selector).replace(/^xpath:/i,'');const result=document.evaluate(xpath,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);return{count:result.snapshotLength}}return{count:globalThis.__blockItSelectorEngine.find(rule.selector).length}}catch(error){return{count:0,error:`${error.name}: ${error.message}`}}})}
async function setSuspended(tabId,value){await chrome.scripting.executeScript({target:{tabId,allFrames:true},world:'ISOLATED',func:enabled=>enabled?sessionStorage.setItem('blockit-rule-audit-suspended','1'):sessionStorage.removeItem('blockit-rule-audit-suspended'),args:[value]})}
function sameRule(a,b){return a.id&&b.id?a.id===b.id:a.selector===b.selector&&a.domain===b.domain}
async function updateStoredRule(rule,change){const {rules=[]}=await chrome.storage.local.get(['rules']);const index=rules.findIndex(item=>sameRule(item,rule));if(index<0)return false;rules[index]={...rules[index],...change,id:rules[index].id||crypto.randomUUID()};Object.assign(rule,rules[index]);await chrome.storage.local.set({rules});return true}
function makeActions(rule,canBind=false){const actions=document.createElement('div');actions.className='result-actions';if(canBind&&!rule.domain){const bind=document.createElement('button');bind.textContent=tr('Привязать к {domain}',{domain:draft.domain});bind.className='bind';bind.addEventListener('click',async()=>{if(await updateStoredRule(rule,{domain:draft.domain})){bind.textContent=tr('Привязано к {domain}',{domain:draft.domain});bind.disabled=true}});actions.append(bind)}if(rule.type==='blockitbuilder'){const edit=document.createElement('button');edit.textContent=tr('Редактировать');edit.className='edit';edit.addEventListener('click',async()=>{const id=rule.id||crypto.randomUUID();if(!rule.id)await updateStoredRule(rule,{id});try{await chrome.scripting.executeScript({target:{tabId:draft.tabId},world:'ISOLATED',func:value=>{let ids=[];try{ids=JSON.parse(sessionStorage.getItem('blockit-editor-excluded-rules')||'[]')}catch{}if(!ids.includes(value))ids.push(value);sessionStorage.setItem('blockit-editor-excluded-rules',JSON.stringify(ids))},args:[id]})}catch{}await chrome.storage.session.set({ruleBuilderDraft:{model:rule.builderModel,editingRule:{id,selector:rule.selector,domain:rule.domain||draft.domain,enabled:rule.enabled!==false},expectedDomain:rule.domain||draft.domain,sourceTabId:draft.tabId,sourceUrl:draft.tabUrl,createdAt:Date.now()}});await chrome.tabs.create({url:chrome.runtime.getURL('rule-builder.html')})});actions.append(edit)}const toggle=document.createElement('button');toggle.textContent=tr(rule.enabled===false?'Включить':'Отключить');toggle.addEventListener('click',async()=>{if(await updateStoredRule(rule,{enabled:rule.enabled===false}))renderInitial()});const del=document.createElement('button');del.className='delete';del.textContent=tr('Удалить');del.addEventListener('click',async()=>{if(!confirm(tr('Удалить это правило?')))return;const {rules=[]}=await chrome.storage.local.get(['rules']);await chrome.storage.local.set({rules:rules.filter(item=>!sameRule(item,rule))});draft.rules=draft.rules.filter(item=>!sameRule(item,rule));renderInitial()});actions.append(toggle,del);return actions}
function makeLoadGrid(values,runs,header=false){const grid=document.createElement('div');grid.className=`load-grid${header?' load-grid-head':''}`;grid.style.setProperty('--runs',runs);for(let index=0;index<runs;index++){const cell=document.createElement('span');cell.textContent=header?tr('Загрузка {count}',{count:index+1}):values?.[index]?.error?tr('Ошибка'):values?.[index]?.count??'—';if(values?.[index]?.error)cell.title=tr('Ошибка при проверке правила.');grid.append(cell)}return grid}
function renderTableHeader(runs){resultsList.style.setProperty('--runs',runs);const header=document.createElement('div');header.className='result-table-head';const rule=document.createElement('div');rule.className='head-rule';rule.textContent=tr('Правило');const loads=document.createElement('div');loads.className='head-loads';const title=document.createElement('strong');title.textContent=tr('Количество найденных элементов');loads.append(title,makeLoadGrid(null,runs,true));const status=document.createElement('div');status.textContent=tr('Статус');const actions=document.createElement('div');actions.textContent=tr('Действия');header.append(rule,loads,status,actions);resultsList.append(header)}
function makeRow(rule,values,runs,badgeClass,badgeText,canBind=false){const row=document.createElement('div');row.className=`result-row${rule.enabled===false?' disabled':''}`;const code=document.createElement('div');code.className='rule-code';code.textContent=ruleLabel(rule);const badge=document.createElement('span');badge.className=`badge${badgeClass?' '+badgeClass:''}`;badge.textContent=rule.enabled===false&&badgeText!==tr('Отключено')?tr('{status} · отключено',{status:badgeText}):badgeText;row.append(code,makeLoadGrid(values,runs),badge,makeActions(rule,canBind));return row}
function renderInitial(){const runs=selectedRuns();resultsList.innerHTML='';renderTableHeader(runs);for(const rule of draft.rules)resultsList.append(makeRow(rule,null,runs,'',tr(rule.enabled===false?'Отключено':'Ожидает')))}
function renderResults(history){const runs=history.length;resultsList.innerHTML='';renderTableHeader(runs);let working=0;draft.rules.forEach((rule,index)=>{const values=history.map(run=>run[index]);const errors=values.some(value=>value.error);const hasMatches=values.some(value=>!value.error&&value.count>0);const unique=new Set(values.map(value=>value.count));let cls,text;if(errors){cls='error';text=tr('Ошибка')}else if(!hasMatches){cls='dead';text=tr('Не сработало')}else if(unique.size>1){cls='unstable';text=tr('Нестабильно');working++}else{cls='ok';text=tr('Работает');working++}resultsList.append(makeRow(rule,values,runs,cls,text,hasMatches&&!rule.domain))});summary.textContent=tr('Работают или срабатывают нестабильно: {working} из {total}',{working,total:draft.rules.length})}
async function resume(){if(!draft?.tabId)return;try{await setSuspended(draft.tabId,false);const {rules=[]}=await chrome.storage.local.get(['rules']);await chrome.scripting.executeScript({target:{tabId:draft.tabId,allFrames:true},world:'ISOLATED',func:savedRules=>{let host=location.hostname.replace(/^www\./,'').toLowerCase();if(!host){try{host=new URL(location.ancestorOrigins?.[0]).hostname.replace(/^www\./,'').toLowerCase()}catch{}}const applicable=savedRules.filter(rule=>{const domain=String(rule.domain||'').replace(/^www\./,'').toLowerCase();return rule.enabled!==false&&(!domain||host===domain||host.endsWith(`.${domain}`))});window.postMessage({source:'blockit',action:'apply-rules',rules:applicable},'*')},args:[rules]})}catch{}}
function combineFrameCounts(frameResults,ruleCount){const totals=Array.from({length:ruleCount},()=>({count:0}));for(const frame of frameResults){const values=frame.result||[];for(let index=0;index<ruleCount;index++){const value=values[index];if(value?.error){totals[index].error=totals[index].error||value.error}else totals[index].count+=value?.count||0}}return totals}
startAudit.addEventListener('click',async()=>{if(!draft?.tabId)return;const runs=selectedRuns(),history=[];startAudit.disabled=true;reloadCount.disabled=true;stabilityEnabled.disabled=true;progressPanel.hidden=false;try{await setSuspended(draft.tabId,true);for(let index=0;index<runs;index++){progressTitle.textContent=tr('Перезагрузка {index} из {total}',{index:index+1,total:runs});progressDetail.textContent=tr('Проверяю {domain}',{domain:draft.domain});progressBar.style.width=`${index/runs*100}%`;const loaded=waitForReload(draft.tabId);await chrome.tabs.reload(draft.tabId);await loaded;await new Promise(resolve=>setTimeout(resolve,2500));const results=await chrome.scripting.executeScript({target:{tabId:draft.tabId,allFrames:true},world:'MAIN',func:countRulesInPage,args:[draft.rules]});history.push(combineFrameCounts(results,draft.rules.length));progressBar.style.width=`${(index+1)/runs*100}%`}renderResults(history);progressTitle.textContent=tr('Проверка завершена');progressDetail.textContent=tr('Выполнено перезагрузок: {count}',{count:runs})}catch(error){console.warn('[BlockIt] Rule audit:',error);progressTitle.textContent=tr('Не удалось завершить проверку');progressDetail.textContent=error.message===tr('Страница загружается слишком долго')?error.message:tr('Повторите проверку позже')}finally{await resume();startAudit.disabled=false;stabilityEnabled.disabled=false;updateTooltip()}});
(async()=>{const stored=await chrome.storage.session.get(['ruleAuditDraft']);draft=stored.ruleAuditDraft||null;if(!draft){siteText.textContent=tr('Нет данных для проверки.');startAudit.disabled=true;resultsList.innerHTML='';const empty=document.createElement('div');empty.className='empty';empty.textContent=tr('Откройте диагностику из списка правил.');resultsList.append(empty);return}siteText.textContent=tr('Сайт: {domain} · Правил: {count}',{domain:draft.domain,count:draft.rules.length});updateTooltip();renderInitial()})();
